# Generated by Django 4.0.3 on 2022-03-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0002_post_thumbnail_alter_journalist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='bio',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
