# Generated by Django 4.0.3 on 2022-04-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0010_category_remove_post_category_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
