# Generated by Django 4.0.4 on 2022-08-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0012_journalist_eng_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='eng_name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
